# ---------- STAGE 1: Build ----------
FROM node:22-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package files
COPY .npmrc ./
COPY package*.json ./

# Install dependencies for build
RUN npm ci

# Copy source and build
COPY . .
RUN npm run build


# ---------- STAGE 2: Runtime ----------
FROM node:22-alpine

# Set working directory
WORKDIR /app

# Set timezone to UTC
ENV TZ=UTC

# Install MongoDB Tools (mongodump)
RUN apk add --no-cache mongodb-tools

# Copy files from builder
COPY .npmrc ./
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/dist ./dist

# Install production dependencies only
RUN npm install --omit=dev --ignore-scripts

# Install additional tools
RUN apk add --no-cache postgresql-client

# Expose application port
EXPOSE 3000

# Health check (using /api/health since global prefix is 'api')
HEALTHCHECK --interval=30s --timeout=3s --start-period=40s --retries=3 \
  CMD node -e "require('http').get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"

# Start the application
CMD ["node", "dist/main.js"]
    #test